### ISSUE TITLE
create a contact message for external contributers

### ISSUE THREAD

**Issue by amchagas** [open-neuroscience/resources#1]
@malinINCF was kind enough to look at our work and take the initiative to contact her networks with information about it. Therefore she has updated the current template contact message, so that it is a bit more formal and in the third person (please correct me if I am wrong!).

She has made the change to the text here https://github.com/open-neuroscience/resources/compare/master...malinINCF:patch-1

After a chat with the other project contributors, we thought it would be nice to have both messages instead of just one! @malinINCF would you mind updating the file name in the message you updated so that your pull request does not overwrite the current one? 

I am happy to chat about this further if you have a different suggestion/opinion for this!

**Comment by ChucklesOnGitHub** [comment]
Hi @malinINCF,

Your contribution was very timely since we are developing an “introductory package” to help engage institutions and societies related to neurosciences with the open neuroscience database.

The package includes a formal email template as a presentation to the institution, with the link to our website and a flyer. The flyer can easily be shared in social media or added to work presentations to advocate for open neuroscience. When applicable, we want the material in the package to be in the native language of the intended recipients to make it more appealing and readily accessible.

So, even though we would like to keep our original template as a first-person contact from open neuro to potential projects in developer platforms (github/hackaday/), we have used your modifications to make a more formal contact email template for institutions/societies/forums/mailing lists. **The package material is hosted here: https://github.com/open-neuroscience/resources/tree/master/promotion.**

We highly appreciate your initiative to spread the word about our project. Do you think any local institutions you might engage with would benefit from a Swedish translation of the material? We are currently organizing an awareness campaign in local institutions and native languages available to us. Please let us know.
